# Generated by Django 5.2.2 on 2025-06-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating',
            new_name='rating_com',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='rating_post',
        ),
    ]
