# Generated by Django 5.2.2 on 2025-06-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating_com',
            field=models.IntegerField(default=0),
        ),
    ]
