# Generated by Django 5.2.2 on 2025-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_comment_rating_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating_com',
            field=models.FloatField(default=0.0),
        ),
    ]
