# Generated by Django 5.2.3 on 2025-09-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_name_en_category_name_ru_post_author_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_ru',
        ),
        migrations.AddField(
            model_name='post',
            name='heading_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
